parameter_defaults:
  OvercloudControllerFlavor: "controller"
  OvercloudComputeFlavor: "compute"
  OvercloudComputeOvsDpdkFlavor: "compute"
  OvercloudComputeOvsDpdkSriovFlavor: "compute"
  OvercloudComputeSriovFlavor: "compute"

  ContainerOpenvswitchNetcontroldImage: "quay.io/netcontrold/netcontrold-py:1.0.13"

  ControllerCount: 1
  ComputeOvsDpdkSriovCount: 1
  ComputeSriovCount: 1

  NtpServer: "clock.redhat.com"
  #TimeZone: Kolkata
  SshServerOptions:
    UseDns: 'no'
    #TenantInterfaceRoutes:
    #  - test1: 1
    #    test2: 2
