resource_registry:
  OS::TripleO::ComputeSriov::Net::SoftwareConfig: nic-configs/computesriov-offload.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: nic-configs/controller-offload.yaml

  
parameter_defaults:
  NeutronBridgeMappings: 'datacentre:br-ex,sriov1:br-offload'
  NeutronNetworkVLANRanges: 'sriov1:502:505'
  NeutronFlatNetworks: 'datacentre,sriov1'

  NovaPCIPassthrough:
  - devname: "ens1f0"
    physical_network: "sriov1"
  - devname: "ens1f1"
    physical_network: ""

