heat_template_version: 2014-10-16

description: >
  This is an example showing how you can do firstboot configuration
  of the nodes via cloud-init.  To enable this, replace the default
  mapping of OS::TripleO::NodeUserData in ../overcloud_resource_registry*

parameters:
  ComputeKernelArgs:
    description: >
      Space seprated list of Kernel args to be update to grub.
      The given args will be appended to existing args of GRUB_CMDLINE_LINUX in file /etc/default/grub
      Example: "intel_iommu=on default_hugepagesz=1GB hugepagesz=1G hugepages=1"
    type: string
    default: ""
  ComputeHostnameFormat:
    type: string
    default: ""
  HostCpusList:
    description: >
      A list or range of physical CPU cores to be tuned.
      The given args will be appended to the tuned cpu-partitioning profile.
      Ex. HostCpusList: '4-12' will tune cores from 4-12
    type: string
    default: ""
  NeutronDpdkCoreList:
    description: >
      List of logical cores for PMD threads. Its mandatory parameter.
    type: string
  NeutronDpdkSocketMemory:
    description: Memory allocated for each socket
    default: ""
    type: string

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: set_dpdk_params}
      - config: {get_resource: compute_kernel_args}

  # Verify the logs on /var/log/cloud-init.log on the overcloud node
  compute_kernel_args:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        str_replace:
          template: |
            #!/bin/bash
            set -x

            FORMAT=$COMPUTE_HOSTNAME_FORMAT
            if [[ -z $FORMAT ]] ; then
              FORMAT="compute" ;
            else
              # Assumption: only %index% and %stackname% are the variables in Host name format
              FORMAT=$(echo $FORMAT | sed  's/\%index\%//g' | sed 's/\%stackname\%//g') ;
            fi
            if [[ $(hostname) == *$FORMAT* ]] ; then

              #################################################################
              # Apply Tuned to if the package is installed
              # Tuned package has to be installed
              if yum  list installed | grep tuned-profiles-cpu-partitioning; then
                tuned_conf_path="/etc/tuned/cpu-partitioning-variables.conf"
                if [ -n "$TUNED_CORES" ]; then
                  grep -q "^isolated_cores" $tuned_conf_path
                  if [ "$?" -eq 0 ]; then
                    sed -i 's/^isolated_cores=.*/isolated_cores=$TUNED_CORES/' $tuned_conf_path
                  else
                    echo "isolated_cores=$TUNED_CORES" >> $tuned_conf_path
                  fi
                  tuned-adm profile cpu-partitioning
                fi
              fi

              #################################################################
              ovs_service_path="/usr/lib/systemd/system/ovs-vswitchd.service"
              grep -q "RuntimeDirectoryMode=.*" $ovs_service_path
              if [ "$?" -eq 0 ]; then
                sed -i 's/RuntimeDirectoryMode=.*/RuntimeDirectoryMode=0775/' $ovs_service_path
              else
                echo "RuntimeDirectoryMode=0775" >> $ovs_service_path
              fi
                grep -Fxq "Group=qemu" $ovs_service_path
              if [ ! "$?" -eq 0 ]; then
                echo "Group=qemu" >> $ovs_service_path
              fi
              grep -Fxq "UMask=0002" $ovs_service_path
              if [ ! "$?" -eq 0 ]; then
                echo "UMask=0002" >> $ovs_service_path
              fi
              ovs_ctl_path='/usr/share/openvswitch/scripts/ovs-ctl'
              grep -q "umask 0002 \&\& start_daemon \"\$OVS_VSWITCHD_PRIORITY\"" $ovs_ctl_path
              if [ ! "$?" -eq 0 ]; then
                sed -i 's/start_daemon \"\$OVS_VSWITCHD_PRIORITY.*/umask 0002 \&\& start_daemon \"$OVS_VSWITCHD_PRIORITY\" \"$OVS_VSWITCHD_WRAPPER\" \"$@\"/' $ovs_ctl_path
              fi

              #################################################################
              # Update the KERNEL ARGS to the grub
              sed 's/^\(GRUB_CMDLINE_LINUX=".*\)"/\1 $KERNEL_ARGS"/g' -i /etc/default/grub ;
              grub2-mkconfig -o /etc/grub2.cfg

              # Sometimes, the IP of the provisioning network is not acquired at the time of
              # cloud-init, which will fail the metadata query, looping for 10seconds to ensure
              # the network connectivity is ready.
              i=0
              while [ $i -lt 5 ]; do
                NETWORK=$(curl -m 10 http://169.254.169.254/openstack/latest/network_data.json)
                if [ $? -eq 0 ]; then
                  # Rebooting without running os-net-config will have default ifcfg scripts which
                  # is boot the interfaces in alphanumberic order and if DHCPDISCOVER of an interface\
                  # fails, then the network.service gets failed and does not try others.
                  # Here we are identifying the provisioning network interface and keep the
                  # BOOTPROTO as dpch and for all other interfaces make it as none. So that
                  # network.service will invoke dhcp only on the provisioning network.
                  # We are identifying the provisioning network using the meta data of the node,
                  # which will provide the mac address of the provisioning network interface.
                  # NOTE: Only one provisioning network interface is supported with this script

                  MAC=$(echo $NETWORK | jq -r ".links[0].ethernet_mac_address")
                  IFACE=$(ip a | grep $MAC -B1 | awk 'NR==1{print $2;}' | cut -d ":" -f1)
                  find /etc/sysconfig/network-scripts/ -name 'ifcfg-*' ! -name 'ifcfg-'$IFACE -type f -exec sed 's/^BOOTPROTO=.*/BOOTPROTO=none/g' -i {} +

                  reboot
                  break
                fi
                sleep 2
                i=`expr $i + 1`
              done

            fi
          params:
            $KERNEL_ARGS: {get_param: ComputeKernelArgs}
            $COMPUTE_HOSTNAME_FORMAT: {get_param: ComputeHostnameFormat}
            $TUNED_CORES: {get_param: HostCpusList}

  set_dpdk_params:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        str_replace:
          template: |
            #!/bin/bash
            set -x
            get_mask()
            {
              core_mask=$1
              IFS_BCK=$IFS
              IFS=','
              for core_mask_seq in $core_mask
              do
                      if [[ "$(echo $core_mask_seq|grep "-")" != "" ]]
                      then
                              seq_start=$(echo $core_mask_seq|awk -F "-" '{print $1}')
                              seq_end=$(echo $core_mask_seq|awk -F "-" '{print $2}')
                              for (( num=$seq_start; num<=$seq_end; num++ ))
                              do
                                      core_mask_new_seq=$(echo -n $core_mask_new_seq $num)
                              done
                      else
                              core_mask_new_seq=$(echo -n $core_mask_new_seq $core_mask_seq)
                      fi
              done
              IFS=$IFS_BCK
              core_mask_new_seq=$(echo $core_mask_new_seq|sed "s/ /,/g")

              maximum_core=0
              for core in $(echo $core_mask_new_seq|sed "s/,/ /g")
              do
                      if (( "$core" > "$maximum_core" ))
                      then
                              maximum_core=$core
                      fi
              done

              i=0
              for core in $(echo $core_mask_new_seq|sed "s/,/ /g")
              do
                      core_array_mask[$i]=$core
                      i=$(($i+1))
              done

              j=0
              for (( i=0; i<=$maximum_core; i++ ))
              do
                      if (( "$i" == "${core_array_mask[$j]}" ))
                      then
                              cpu_bit_mask=$(echo 1$cpu_bit_mask)
                              j=$(($j+1))
                      else
                              cpu_bit_mask=$(echo 0$cpu_bit_mask)
                      fi
              done
              echo $(printf '%x\n' "$((2#$cpu_bit_mask))")
            }
            FORMAT=$COMPUTE_HOSTNAME_FORMAT
            if [[ -z $FORMAT ]] ; then
              FORMAT="compute" ;
            else
              # Assumption: only %index% and %stackname% are the variables in Host name format
              FORMAT=$(echo $FORMAT | sed  's/\%index\%//g' | sed 's/\%stackname\%//g') ;
            fi
            if [[ $(hostname) == *$FORMAT* ]] ; then
              pmd_cpu_mask=$( get_mask $PMD_CORES )
              host_cpu_mask=$( get_mask $TUNED_CORES )
              ovs-vsctl --no-wait set Open_vSwitch . other_config:dpdk-init=true
              ovs-vsctl --no-wait set Open_vSwitch . other_config:dpdk-socket-mem=$SOCKET_MEMORY
              ovs-vsctl --no-wait set Open_vSwitch . other_config:pmd-cpu-mask=$pmd_cpu_mask
              ovs-vsctl --no-wait set Open_vSwitch . other_config:dpdk-lcore-mask=$host_cpu_mask
            fi
          params:
            $COMPUTE_HOSTNAME_FORMAT: {get_param: ComputeHostnameFormat}
            $TUNED_CORES: {get_param: HostCpusList}
            $PMD_CORES: {get_param: NeutronDpdkCoreList}
            $SOCKET_MEMORY: {get_param: NeutronDpdkSocketMemory}

outputs:
  # This means get_resource from the parent template will get the userdata, see:
  # http://docs.openstack.org/developer/heat/template_guide/composition.html#making-your-template-resource-more-transparent
  # Note this is new-for-kilo, an alternative is returning a value then using
  # get_attr in the parent template instead.
  OS::stack_id:
    value: {get_resource: userdata}

