resource_registry:
  OS::TripleO::ComputeSriov::Net::SoftwareConfig: nic-configs/computesriov-offload.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: nic-configs/controller.yaml

parameter_defaults:
  NovaPCIPassthrough:
  - devname: "p1p1"
    physical_network: "sriov1"
  - devname: "p1p2"
    physical_network: null

  ComputeSriovParameters:
    OvsOffload: True
