parameter_defaults:
  ControllerCount: 1
  ComputeCount: 1
  OvercloudControlFlavor: control
  OvercloudComputeFlavor: compute

  # NeutronBridgeMappings translates to neutron::agents::ml2::ovs::bridge_mappings
  NeutronBridgeMappings: "datacentre:br-ex,dpdknet:br-link"
  # NeutronFlatNetworks translates to neutron::plugins::ml2::flat_networks
  NeutronFlatNetworks: "datacentre"
  # NeutronNetworkVLANRanges translates to neutron::plugins::ml2::network_vlan_ranges
  NeutronNetworkVLANRanges: "dpdknet:100:103"
  # NeutronNetworkType translates to neutron::plugins::ml2::tenant_network_types
  NeutronNetworkType: ['vlan']
  # NeutronTunnelTypes translates to neutron::agents::ml2::ovs::tunnel_types
  NeutronTunnelTypes: ""
