parameter_defaults:
  ComputeOvsDpdkParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=64 intel_iommu=on iommu=pt"
    TunedProfileName: "cpu-partitioning"
    IsolCpusList: "2-7"

  OvsDpdkSocketMemory: "1024,1024"
  OvsDpdkMemoryChannels: "4"
  NovaReservedHostMemory: 4096

  OvsPmdCoreList: "2,3"
  OvsDpdkCoreList: "4,5"
  NovaVcpuPinSet: ['6','7']
  NumDpdkInterfaceRxQueues: 2
  NeutronGlobalPhysnetMtu: 2000
