resource_registry:
  OS::TripleO::Compute::Net::SoftwareConfig: nic-configs/computeovsdpdk.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: nic-configs/controller.yaml
  OS::TripleO::NodeUserData: first-boot.yaml
  OS::TripleO::NodeExtraConfigPost: post-install.yaml

parameter_defaults:
  ControlPlaneDefaultRoute: "172.150.0.1"
  ControlPlaneSubnetCidr: "24"
  DnsServers: ['10.11.5.19']
  EC2MetadataIp: "172.150.0.1"

  ExternalAllocationPools: [{'start': '10.9.88.200', 'end': '10.9.88.211'}]
  ExternalNetCidr: "10.9.88.0/24"
  #ExternalNetworkVlanID: 135
  NeutronExternalNetworkBridge: "''"
  ExternalInterfaceDefaultRoute: "10.9.88.254"

  InternalApiNetCidr: 10.150.81.0/24
  StorageNetCidr: 10.150.82.0/24
  StorageMgmtNetCidr: 10.150.83.0/24
  TenantNetCidr: 10.150.84.0/24
  InternalApiNetworkVlanID: 131
  StorageNetworkVlanID: 132
  StorageMgmtNetworkVlanID: 1333
  TenantNetworkVlanID: 134
  InternalApiAllocationPools: [{'start': '10.150.81.20', 'end': '10.150.81.200'}]
  StorageAllocationPools: [{'start': '10.150.82.20', 'end': '10.150.82.200'}]
  StorageMgmtAllocationPools: [{'start': '10.150.83.20', 'end': '10.150.83.200'}]
  TenantAllocationPools: [{'start': '10.150.84.20', 'end': '10.150.84.200'}]

  ControllerCount: 1
  ComputeCount: 2

  # NeutronBridgeMappings translates to neutron::agents::ml2::ovs::bridge_mappings
  NeutronBridgeMappings: "datacentre:br-ex,dpdknet:br-link"
  # NeutronFlatNetworks translates to neutron::plugins::ml2::flat_networks
  NeutronFlatNetworks: "datacentre"
  # NeutronNetworkVLANRanges translates to neutron::plugins::ml2::network_vlan_ranges
  NeutronNetworkVLANRanges: "dpdknet:210:214"
  # NeutronNetworkType translates to neutron::plugins::ml2::tenant_network_types
  NeutronNetworkType: ['vlan']
  # NeutronTunnelTypes translates to neutron::agents::ml2::ovs::tunnel_types
  NeutronTunnelTypes: ""

  NeutronDpdkMemoryChannels: "4"

  NeutronDatapathType: "netdev"
  NeutronVhostuserSocketDir: "/var/run/openvswitch"
  NeutronDpdkSocketMemory: "'1024,1024'"
  NeutronDpdkDriverType: "vfio-pci"
  NovaReservedHostMemory: 4096
  NovaSchedulerDefaultFilters: "RamFilter,ComputeFilter,AvailabilityZoneFilter,ComputeCapabilitiesFilter,ImagePropertiesFilter,PciPassthroughFilter,NUMATopologyFilter,AggregateInstanceExtraSpecsFilter"
  ComputeKernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=64 intel_iommu=on"

  NeutronDpdkCoreList: "'10,11,22,23'"
  HostCpusList: "'0,1,2,3,4,5,6,7,8,9'"
  NovaVcpuPinSet: ['12-21','24-87']

  # TODO: Check if this configuration can be avoided
  # HostIsolatedCoreList = NeutronDpdkCoreList + NovaVcpuPinSet
  HostIsolatedCoreList: "10-87"
