heat_template_version: rocky
description: >
  Software Config to drive os-net-config to configure multiple interfaces for the Controller role.
parameters:
  ControlPlaneIp:
    default: ''
    description: IP address/subnet on the ctlplane network
    type: string
  ControlPlaneSubnetCidr:
    default: ''
    description: >
      The subnet CIDR of the control plane network. (The parameter is
      automatically resolved from the ctlplane subnet's cidr attribute.)
    type: string
  ControlPlaneDefaultRoute:
    default: ''
    description: The default route of the control plane network. (The parameter
      is automatically resolved from the ctlplane subnet's gateway_ip attribute.)
    type: string

  StorageIpSubnet:
    default: ''
    description: IP address/subnet on the storage network
    type: string
  StorageNetworkVlanID:
    default: 131
    description: Vlan ID for the storage network traffic.
    type: number
  StorageInterfaceDefaultRoute:
    default: '172.16.16.1'
    description: default route for the storage network
    type: string
  StorageInterfaceRoutes:
    default: []
    description: >
      Routes for the storage network traffic.
      JSON route e.g. [{'destination':'10.0.0.0/16', 'nexthop':'10.0.0.1'}]
      Unless the default is changed, the parameter is automatically resolved
      from the subnet host_routes attribute.
    type: json
  StorageLeaf1IpSubnet:
    default: ''
    description: IP address/subnet on the storage1 network
    type: string
  StorageLeaf1NetworkVlanID:
    default: 131
    description: Vlan ID for the storage1 network traffic.
    type: number
  StorageLeaf1InterfaceDefaultRoute:
    default: '172.16.17.1'
    description: default route for the storage1 network
    type: string
  StorageLeaf1InterfaceRoutes:
    default: []
    description: >
      Routes for the storage1 network traffic.
      JSON route e.g. [{'destination':'10.0.0.0/16', 'nexthop':'10.0.0.1'}]
      Unless the default is changed, the parameter is automatically resolved
      from the subnet host_routes attribute.
    type: json
  StorageMgmtIpSubnet:
    default: ''
    description: IP address/subnet on the storage_mgmt network
    type: string
  StorageMgmtNetworkVlanID:
    default: 132
    description: Vlan ID for the storage_mgmt network traffic.
    type: number
  StorageMgmtInterfaceDefaultRoute:
    default: '172.16.48.1'
    description: default route for the storage_mgmt network
    type: string
  StorageMgmtInterfaceRoutes:
    default: []
    description: >
      Routes for the storage_mgmt network traffic.
      JSON route e.g. [{'destination':'10.0.0.0/16', 'nexthop':'10.0.0.1'}]
      Unless the default is changed, the parameter is automatically resolved
      from the subnet host_routes attribute.
    type: json
  StorageMgmtLeaf1IpSubnet:
    default: ''
    description: IP address/subnet on the storage_mgmt1 network
    type: string
  StorageMgmtLeaf1NetworkVlanID:
    default: 132
    description: Vlan ID for the storage_mgmt1 network traffic.
    type: number
  StorageMgmtLeaf1InterfaceDefaultRoute:
    default: '172.16.49.1'
    description: default route for the storage_mgmt1 network
    type: string
  StorageMgmtLeaf1InterfaceRoutes:
    default: []
    description: >
      Routes for the storage_mgmt1 network traffic.
      JSON route e.g. [{'destination':'10.0.0.0/16', 'nexthop':'10.0.0.1'}]
      Unless the default is changed, the parameter is automatically resolved
      from the subnet host_routes attribute.
    type: json
  InternalApiIpSubnet:
    default: ''
    description: IP address/subnet on the internal_api network
    type: string
  InternalApiNetworkVlanID:
    default: 134
    description: Vlan ID for the internal_api network traffic.
    type: number
  InternalApiInterfaceDefaultRoute:
    default: '172.16.32.1'
    description: default route for the internal_api network
    type: string
  InternalApiInterfaceRoutes:
    default: []
    description: >
      Routes for the internal_api network traffic.
      JSON route e.g. [{'destination':'10.0.0.0/16', 'nexthop':'10.0.0.1'}]
      Unless the default is changed, the parameter is automatically resolved
      from the subnet host_routes attribute.
    type: json
  InternalApiLeaf1IpSubnet:
    default: ''
    description: IP address/subnet on the internal_api1 network
    type: string
  InternalApiLeaf1NetworkVlanID:
    default: 134
    description: Vlan ID for the internal_api1 network traffic.
    type: number
  InternalApiLeaf1InterfaceDefaultRoute:
    default: '172.16.33.1'
    description: default route for the internal_api1 network
    type: string
  InternalApiLeaf1InterfaceRoutes:
    default: []
    description: >
      Routes for the internal_api1 network traffic.
      JSON route e.g. [{'destination':'10.0.0.0/16', 'nexthop':'10.0.0.1'}]
      Unless the default is changed, the parameter is automatically resolved
      from the subnet host_routes attribute.
    type: json
  TenantIpSubnet:
    default: ''
    description: IP address/subnet on the tenant network
    type: string
  TenantNetworkVlanID:
    default: 133
    description: Vlan ID for the tenant network traffic.
    type: number
  TenantInterfaceDefaultRoute:
    default: '172.16.0.1'
    description: default route for the tenant network
    type: string
  TenantInterfaceRoutes:
    default: []
    description: >
      Routes for the tenant network traffic.
      JSON route e.g. [{'destination':'10.0.0.0/16', 'nexthop':'10.0.0.1'}]
      Unless the default is changed, the parameter is automatically resolved
      from the subnet host_routes attribute.
    type: json
  TenantLeaf1IpSubnet:
    default: ''
    description: IP address/subnet on the tenant1 network
    type: string
  TenantLeaf1NetworkVlanID:
    default: 133
    description: Vlan ID for the tenant1 network traffic.
    type: number
  TenantLeaf1InterfaceDefaultRoute:
    default: '172.16.1.1'
    description: default route for the tenant1 network
    type: string
  TenantLeaf1InterfaceRoutes:
    default: []
    description: >
      Routes for the tenant1 network traffic.
      JSON route e.g. [{'destination':'10.0.0.0/16', 'nexthop':'10.0.0.1'}]
      Unless the default is changed, the parameter is automatically resolved
      from the subnet host_routes attribute.
    type: json
  ExternalIpSubnet:
    default: ''
    description: IP address/subnet on the external network
    type: string
  ExternalNetworkVlanID:
    default: 10
    description: Vlan ID for the external network traffic.
    type: number
  ExternalInterfaceDefaultRoute:
    default: '10.9.88.254'
    description: default route for the external network
    type: string
  ExternalInterfaceRoutes:
    default: []
    description: >
      Routes for the external network traffic.
      JSON route e.g. [{'destination':'10.0.0.0/16', 'nexthop':'10.0.0.1'}]
      Unless the default is changed, the parameter is automatically resolved
      from the subnet host_routes attribute.
    type: json
  ManagementIpSubnet:
    default: ''
    description: IP address/subnet on the management network
    type: string
  ManagementNetworkVlanID:
    default: 60
    description: Vlan ID for the management network traffic.
    type: number
  ManagementInterfaceRoutes:
    default: []
    description: >
      Routes for the management network traffic.
      JSON route e.g. [{'destination':'10.0.0.0/16', 'nexthop':'10.0.0.1'}]
      Unless the default is changed, the parameter is automatically resolved
      from the subnet host_routes attribute.
    type: json
  DnsServers: # Override this via parameter_defaults
    default: []
    description: >
      DNS servers to use for the Overcloud (2 max for some implementations).
      If not set the nameservers configured in the ctlplane subnet's
      dns_nameservers attribute will be used.
    type: comma_delimited_list
  EC2MetadataIp:
    default: ''
    description: The IP address of the EC2 metadata server. (The parameter
      is automatically resolved from the ctlplane subnet's host_routes attribute.)
    type: string

  # Manual Addition
  InternalApiNetCidr:
    description: Cidr for the internal_api network.
    type: string
  TenantNetCidr:
    description: Cidr for the tenant network.
    type: string
  StorageNetCidr:
    description: Cidr for the storage network.
    type: string
  StorageMgmtNetCidr:
    description: Cidr for the storage_mgmt network.
    type: string
  InternalApiLeaf1NetCidr:
    description: Cidr for the internal_api1 network.
    type: string
  TenantLeaf1NetCidr:
    description: Cidr for the tenant1 network.
    type: string
  StorageLeaf1NetCidr:
    description: Cidr for the storage1 network.
    type: string
  StorageMgmtLeaf1NetCidr:
    description: Cidr for the storage_mgmt1 network.
    type: string
  ControlPlaneLeaf1SubnetCidr:
    default: ''
    description: >
      The subnet CIDR of the control plane network. (The parameter is
      automatically resolved from the ctlplane subnet's cidr attribute.)
    type: string
  ControlPlaneLeaf1DefaultRoute:
    default: ''
    description: The default route of the control plane network. (The parameter
      is automatically resolved from the ctlplane subnet's gateway_ip attribute.)
    type: string
  Leaf1EC2MetadataIp:
    default: ''
    description: The IP address of the EC2 metadata server. (The parameter
      is automatically resolved from the ctlplane subnet's host_routes attribute.)
    type: string

resources:
  OsNetConfigImpl:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        str_replace:
          template:
            get_file: /usr/share/openstack-tripleo-heat-templates/network/scripts/run-os-net-config.sh
          params:
            $network_config:
              network_config:
              - type: interface
                name: eth0
                use_dhcp: false
                dns_servers:
                  get_param: DnsServers
                addresses:
                - ip_netmask:
                    list_join:
                    - /
                    - - get_param: ControlPlaneIp
                      - get_param: ControlPlaneSubnetCidr
                routes:
                - ip_netmask: 169.254.169.254/32
                  next_hop:
                    get_param: EC2MetadataIp
                - ip_netmask: 0.0.0.0/0
                  next_hop:
                    get_param: ControlPlaneDefaultRoute
                  default: true
              - type: interface
                name: eth3
                use_dhcp: false
                defroute: false
              - type: interface
                name: eth1
                use_dhcp: false
                defroute: false
              - type: vlan
                vlan_id:
                  get_param: InternalApiNetworkVlanID
                device: eth1
                addresses:
                - ip_netmask:
                    get_param: InternalApiIpSubnet
              - type: vlan
                vlan_id:
                  get_param: StorageNetworkVlanID
                device: eth1
                addresses:
                - ip_netmask:
                    get_param: StorageIpSubnet
              - type: ovs_bridge
                name: br-tenant
                use_dhcp: false
                addresses:
                - ip_netmask:
                    get_param: TenantIpSubnet
                ovs_extra:
                  - str_replace:
                      template: set port br-tenant tag=_VLAN_TAG_
                      params:
                        _VLAN_TAG_:
                          get_param: TenantNetworkVlanID
                members:
                - type: interface
                  name: eth2

outputs:
  OS::stack_id:
    description: The OsNetConfigImpl resource.
    value:
      get_resource: OsNetConfigImpl

